# Generated by Django 4.2.19 on 2025-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.DateField(verbose_name='год постройки'),
        ),
    ]
