# Generated by Django 4.2.19 on 2025-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='square',
            field=models.IntegerField(verbose_name='Сколько кв метров'),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(verbose_name='Год постройки'),
        ),
    ]
