# Generated by Django 4.2.19 on 2025-02-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descrip_page', '0003_comments_created_at_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='img',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
